### ISSUE TITLE
Sending encrypted volume on ZFSoL 0.8.1 does not work

### ISSUE THREAD

**Issue by kvoit** [bolthole/zrep#117] opened 2019-06-28 20:09 UTC
As a followup on #116, I ran into the next problem with sending an encrypted volume.

With the --raw option, I run into the error message
`zfs receive -F cannot be used to destroy an encrypted filesystem or overwrite an unencrypted one with an encrypted one`
during init.
I have tracked this down to the fact that with my zfs version, Z_HAS_REC_O is not detected, leading to an unencrypted filesystem being created before sending the initial snapshot.

I have forced Z_HAS_REC_O=1 in the init function, and my intitial snapshot is currently transferring (and will be for most of the rest of the weekend).

`zfs help` contrains this, so I believe the detection code is insufficient?:

        receive [-vnsFhu] [-o <property>=<value>] ... [-x <property>] ...
            <filesystem|volume|snapshot>
        receive [-vnsFhu] [-o <property>=<value>] ... [-x <property>] ... 
            [-d | -e] <filesystem>
        receive -A <filesystem|volume>

Also, either I misread it, or this comment is now wrong:
```
# Note that at the current time, this does NOT get used, for
#   the initial "zrep init" zfs send. If this gets reported as
#   a problem, that may change
#ZREP_SEND_FLAGS=-c
```
which confused me a bit during investigation of the issue. The send command does have the variable, even in init.

**Comment by ppbrown** [comment] 2019-08-06 06:48
Hmm.
You said that receive -o detection isnt working on your system.
I believe that the change I made afterwards, on July 12 probably fixes this issue for you. 
Change 8383a6661f864b9754932eca401b6e14635a0542
Closing this with that assumption. Please reopen if the problem is still there for you.

**Closed by ppbrown** 2019-08-06 06:48 UTC
